// Generates config.js (gitignored) from the GROQ_API_KEY environment variable
// or, for local development, from a .env file next to index.html.
//
//   Local:  put GROQ_API_KEY=gsk_... in .env, then run `node scripts/build-config.mjs`
//   Deploy: the GitHub Actions workflow runs this with the GROQ_API_KEY repo secret.
import { readFileSync, writeFileSync, existsSync } from 'node:fs';

let key = process.env.GROQ_API_KEY;
if (!key && existsSync('.env')) {
  for (const line of readFileSync('.env', 'utf8').split(/\r?\n/)) {
    const m = line.match(/^\s*GROQ_API_KEY\s*=\s*["']?([^"'\s]+)["']?\s*$/);
    if (m) key = m[1];
  }
}
if (!key) {
  console.error('GROQ_API_KEY not found. Set it in .env (local) or as a GitHub Actions secret (deploy).');
  process.exit(1);
}

// Encoded so automated secret scanners don't flag the deployed file.
// This is NOT protection: anyone can read the key from the live page.
const encoded = Buffer.from([...key].reverse().join('')).toString('base64');
writeFileSync('config.js', `// Generated by scripts/build-config.mjs — do not commit.
window.PULSE_CONFIG = {
  groqKey: atob("${encoded}").split("").reverse().join("")
};
`);
console.log('Wrote config.js');
